---
- import_tasks: build_depends.yml

- import_tasks: set_facts.yml

- name: Install rbenv system-wide
  include_tasks: system_install.yml
  when: rbenv_install == "system"

- name: Install rbenv for selected users
  include_tasks: user_install.yml
  when: rbenv_install != "system"
