---
- import_tasks: build_depends.yml
- name: Set rbenv_owner
  set_fact:
    rbenv_owner: '{{ rbenv_owner | default("root", true) }}'

- name: Set tmp directory path
  set_fact:
    rbenv_tmpdir: "{{ ansible_env.TMPDIR | default('/tmp') }}"
  when: rbenv_tmpdir is undefined

- name: Install rbenv system-wide
  include_tasks: system_install.yml
  when: rbenv_install == "system"

- name: Install rbenv for selected users
  include_tasks: user_install.yml
  when: rbenv_install != "system"
