- name: Set rbenv_owner
  set_fact:
    rbenv_owner: '{{ rbenv_owner | default("root", true) }}'

- name: Set tmp directory path
  set_fact:
    rbenv_tmpdir: "{{ ansible_env.TMPDIR | default('/tmp') }}"
  when: rbenv_tmpdir is undefined

- name: Select rbenv plugins for installation
  set_fact:
    rbenv_plugins_keys: '{{ rbenv_plugins_keys }} + ["rbenv_plugin_{{ item }}"]'
  loop: "{{ rbenv_plugins }}"

- name: Gather rbenv plugins specifications
  set_fact:
    rbenv_plugins_specs: '{{ rbenv_plugins_specs }} + [{{ vars[item] }}]'
  loop: "{{ rbenv_plugins_keys }}"
